name: test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    if: github.repository != 'awesome-foundation/aws-config-d' # Do not run in the template repository — you may delete this line, it has no effect in your repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash test.sh
